import {
  Conversation,
  Message,
  Lead,
  KnowledgeItem,
  LearningItem,
  ManagedLink,
  ObjectionItem,
  AiPersonality,
  AiLog,
  SystemDiagnostics,
  AiProvider,
} from "@/types";

export const initialPersonalities: AiPersonality[] = [
  {
    id: "p1",
    name: "Luxury & Exclusive",
    description: "Refined, sophisticated, highly courteous tone designed for high-ticket clients.",
    tone: "Polished, elite, respectful",
    greetingStyle: "Welcome to Zawr Industries. It is a pleasure to assist you.",
    formality: "high",
    emojiUsage: "none",
    ctaStyle: "Invite to an exclusive private strategy call via {{meeting}}",
    isDefault: true,
  },
  {
    id: "p2",
    name: "Consultative Sales",
    description: "Proactive, value-driven sales agent focused on identifying customer needs and closing deals.",
    tone: "Persuasive, authoritative, helpful",
    greetingStyle: "Hi! Thanks for reaching out to Zawr. How can we accelerate your business today?",
    formality: "medium",
    emojiUsage: "minimal",
    ctaStyle: "Direct recommendation to book a consultation at {{meeting}}",
  },
  {
    id: "p3",
    name: "Minimal & Direct",
    description: "Crisp, concise, Vercel-inspired clarity with zero fluff.",
    tone: "Direct, precise, efficient",
    greetingStyle: "Hello. How can Zawr assist your team?",
    formality: "medium",
    emojiUsage: "none",
    ctaStyle: "View portfolio at {{portfolio}} or schedule at {{meeting}}",
  },
];

export const initialManagedLinks: ManagedLink[] = [
  {
    id: "l1",
    key: "{{website}}",
    title: "Official Website",
    url: "https://zawr.ai",
    description: "Main company homepage and overview",
    clicks: 1420,
    updatedAt: "2026-07-01T10:00:00Z",
  },
  {
    id: "l2",
    key: "{{pricing}}",
    title: "Pricing & Plans",
    url: "https://zawr.ai/pricing",
    description: "Complete service tier and package breakdowns",
    clicks: 890,
    updatedAt: "2026-07-05T12:00:00Z",
  },
  {
    id: "l3",
    key: "{{meeting}}",
    title: "Executive Strategy Meeting",
    url: "https://cal.com/zawr/strategy-session",
    description: "Direct 30-min strategy consultation calendar link",
    clicks: 430,
    updatedAt: "2026-07-10T15:30:00Z",
  },
  {
    id: "l4",
    key: "{{portfolio}}",
    title: "Case Studies & Portfolio",
    url: "https://zawr.ai/portfolio",
    description: "Verified results and past client work",
    clicks: 610,
    updatedAt: "2026-07-12T09:15:00Z",
  },
  {
    id: "l5",
    key: "{{catalog}}",
    title: "Service Catalog",
    url: "https://zawr.ai/services-catalog.pdf",
    description: "Downloadable PDF brochure of all enterprise solutions",
    clicks: 310,
    updatedAt: "2026-07-14T11:00:00Z",
  },
];

export const initialKnowledge: KnowledgeItem[] = [
  {
    id: "k1",
    title: "Zawr Enterprise AI Implementation Services",
    category: "services",
    content: "Zawr Industries builds custom AI assistants, automated sales funnels, and enterprise knowledge agents for growing brands. Standard implementation takes 5-7 business days. Packages range from Growth ($2,500/mo) to Enterprise Custom ($8,000/mo). Check details at {{pricing}}.",
    sourceType: "text",
    version: 1,
    isActive: true,
    indexedAt: "2026-07-01T00:00:00Z",
    updatedAt: "2026-07-01T00:00:00Z",
  },
  {
    id: "k2",
    title: "Pricing Tiers & Inclusions",
    category: "pricing",
    content: "Growth Tier: $2,500/mo includes up to 50,000 monthly messages, 1 AI channel (Instagram or Web), basic CRM integration. Scale Tier: $4,500/mo includes 150,000 messages, 3 channels, human-in-the-loop queue, advanced sales scoring. Enterprise: Custom quote starting at $8,000/mo with custom SLA and dedicated fine-tuned models. See {{pricing}}.",
    sourceType: "text",
    version: 2,
    isActive: true,
    indexedAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-10T00:00:00Z",
  },
  {
    id: "k3",
    title: "Guarantees & Refund Policy",
    category: "policies",
    content: "Zawr offers a 14-day performance guarantee. If the AI assistant does not achieve at least a 30% reduction in response time and qualify at least 15 leads during onboarding, client receives a 100% refund of setup fees. Terms available at {{website}}/terms.",
    sourceType: "text",
    version: 1,
    isActive: true,
    indexedAt: "2026-07-03T00:00:00Z",
    updatedAt: "2026-07-03T00:00:00Z",
  },
  {
    id: "k4",
    title: "Creator Alliance Program",
    category: "sales",
    content: "For creators with >50k verified Instagram followers, Zawr provides revenue-share partnerships where we deploy AI Sales Assistants to monetized DMs. Creators get 25% revenue split on high-ticket sales generated via DM funnels.",
    sourceType: "text",
    version: 1,
    isActive: true,
    indexedAt: "2026-07-05T00:00:00Z",
    updatedAt: "2026-07-05T00:00:00Z",
  },
];

export const initialObjections: ObjectionItem[] = [
  {
    id: "o1",
    category: "price",
    objection: "Your $2,500/mo plan is too expensive for our current stage.",
    approvedStrategy: "Reframe as ROI investment. Point out that missing 3 high-intent Instagram leads costs more than the monthly fee.",
    counterScript: "I completely understand budget considerations. Most of our clients recover the monthly investment within the first 10 days by capturing high-intent DM leads that would otherwise drop off. Have a quick look at {{portfolio}} to see case study metrics, or let's discuss a scaled option at {{meeting}}.",
  },
  {
    id: "o2",
    category: "trust",
    objection: "Will the AI sound robotic or hallucinate false information to our customers?",
    approvedStrategy: "Emphasize Zawr's strict Zero-Hallucination policy and Human-in-the-Loop confidence system.",
    counterScript: "Great question! Zawr uses a zero-hallucination RAG architecture. If confidence is under 95%, responses require owner approval or route to your learning queue. It never fabricates pricing or policies. Try our demo or book a session at {{meeting}}.",
  },
];

export const initialLeads: Lead[] = [
  {
    id: "lead-1",
    instagramUsername: "alex_growth",
    name: "Alex Rivera",
    email: "alex@growthagency.co",
    phone: "+1 555-0192",
    company: "GrowthAgency Co",
    industry: "E-Commerce Marketing",
    budgetRange: "$5,000 - $10,000/mo",
    timeline: "Immediate (Next 7 days)",
    decisionMaker: true,
    leadScore: 94,
    leadTemperature: "hot",
    status: "qualified",
    expectedValue: 5400,
    priority: "high",
    tags: ["High Intent", "E-Commerce", "Immediate"],
    notes: "Wants full Instagram DM automation with CRM sync. High intent to close.",
    aiSummary: "Prospect is founder of 12-person agency handling 20+ store IG accounts. Highly interested in Scale Tier.",
    conversationCount: 8,
    lastContactAt: "2026-07-20T14:20:00Z",
  },
  {
    id: "lead-2",
    instagramUsername: "sarah_designs",
    name: "Sarah Chen",
    email: "sarah@chenstudio.com",
    company: "Chen Design Studio",
    industry: "Luxury Interior Architecture",
    budgetRange: "$2,500 - $5,000/mo",
    timeline: "Within 30 days",
    decisionMaker: true,
    leadScore: 82,
    leadTemperature: "warm",
    status: "meeting_booked",
    expectedValue: 3000,
    priority: "medium",
    tags: ["Luxury", "Design", "VIP"],
    notes: "Meeting booked for Thursday. Wants Luxury personality response style.",
    aiSummary: "Inquired about qualifying high-net-worth clients via DM prior to consultations.",
    conversationCount: 5,
    lastContactAt: "2026-07-20T11:15:00Z",
  },
  {
    id: "lead-3",
    instagramUsername: "elena_investor",
    name: "Elena Rostova",
    email: "elena@vanguardcap.io",
    company: "Vanguard Partners",
    industry: "Venture Capital / Investment",
    budgetRange: "Enterprise Custom",
    timeline: "Evaluating",
    decisionMaker: true,
    leadScore: 98,
    leadTemperature: "hot",
    status: "in_discussion",
    expectedValue: 12000,
    priority: "vip",
    tags: ["Investor", "VIP", "Enterprise"],
    notes: "Inquired about potential partnership & enterprise alliance.",
    aiSummary: "Investor interested in Zawr platform capabilities and white-label enterprise licensing.",
    conversationCount: 12,
    lastContactAt: "2026-07-20T15:45:00Z",
  },
];

export const initialConversations: Conversation[] = [
  {
    id: "conv-1",
    channel: "instagram",
    customerUsername: "alex_growth",
    customerName: "Alex Rivera",
    customerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    lastMessageText: "Can we connect the AI to our custom webhooks for instant CRM lead scoring?",
    lastMessageAt: "2026-07-20T14:20:00Z",
    unreadCount: 1,
    tags: ["High Intent", "API Question"],
    leadScore: 94,
    leadTemperature: "hot",
    aiSummary: "Asked about custom webhooks and API lead scoring sync. AI auto-replied with high confidence.",
    assignedPersonalityId: "p2",
    status: "active",
  },
  {
    id: "conv-2",
    channel: "instagram",
    customerUsername: "sarah_designs",
    customerName: "Sarah Chen",
    customerAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150",
    lastMessageText: "Thanks! I booked the strategy call for Thursday at 3 PM.",
    lastMessageAt: "2026-07-20T11:15:00Z",
    unreadCount: 0,
    tags: ["Meeting Booked", "Luxury"],
    leadScore: 82,
    leadTemperature: "warm",
    aiSummary: "Confirmed meeting booking via {{meeting}}. Guided successfully.",
    assignedPersonalityId: "p1",
    status: "starred",
  },
  {
    id: "conv-3",
    channel: "instagram",
    customerUsername: "marcus_retail",
    customerName: "Marcus Vance",
    customerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150",
    lastMessageText: "Do you support custom Shopify Plus checkout extensions in your Instagram DM flow?",
    lastMessageAt: "2026-07-20T15:02:00Z",
    unreadCount: 1,
    tags: ["Unknown Question", "Shopify"],
    leadScore: 65,
    leadTemperature: "warm",
    aiSummary: "Asked specific Shopify Plus integration question not found in KB. Escalated to Owner Learning Queue (Confidence: 62%).",
    assignedPersonalityId: "p3",
    status: "pending",
  },
];

export const initialMessages: Record<string, Message[]> = {
  "conv-1": [
    {
      id: "m101",
      conversationId: "conv-1",
      sender: "customer",
      content: "Hey Zawr team! We manage 20+ high-volume Instagram accounts. What's your monthly pricing?",
      confidenceScore: 100,
      decisionRoute: "auto_reply",
      createdAt: "2026-07-20T14:15:00Z",
    },
    {
      id: "m102",
      conversationId: "conv-1",
      sender: "ai",
      content: "Hello Alex! Thanks for reaching out to Zawr. For multi-account agencies, our Scale Tier ($4,500/mo) includes 150,000 monthly messages across channels, automated lead scoring, and dedicated RAG setup. You can review all details at {{pricing}}.",
      confidenceScore: 98,
      decisionRoute: "auto_reply",
      tokensUsed: 142,
      latencyMs: 840,
      provider: "gemini",
      createdAt: "2026-07-20T14:16:00Z",
    },
    {
      id: "m103",
      conversationId: "conv-1",
      sender: "customer",
      content: "Can we connect the AI to our custom webhooks for instant CRM lead scoring?",
      confidenceScore: 100,
      decisionRoute: "auto_reply",
      createdAt: "2026-07-20T14:20:00Z",
    },
  ],
  "conv-2": [
    {
      id: "m201",
      conversationId: "conv-2",
      sender: "customer",
      content: "Hello, do you assist luxury interior design studios with client qualification on IG?",
      confidenceScore: 100,
      decisionRoute: "auto_reply",
      createdAt: "2026-07-20T11:00:00Z",
    },
    {
      id: "m202",
      conversationId: "conv-2",
      sender: "ai",
      content: "Welcome to Zawr Industries. It is a pleasure to assist you. Indeed, our Luxury AI personality is specially configured to filter high-net-worth inquiries and guide qualified clients directly to your calendar at {{meeting}}.",
      confidenceScore: 96,
      decisionRoute: "auto_reply",
      tokensUsed: 110,
      latencyMs: 760,
      provider: "gemini",
      createdAt: "2026-07-20T11:02:00Z",
    },
    {
      id: "m203",
      conversationId: "conv-2",
      sender: "customer",
      content: "Thanks! I booked the strategy call for Thursday at 3 PM.",
      confidenceScore: 100,
      decisionRoute: "auto_reply",
      createdAt: "2026-07-20T11:15:00Z",
    },
  ],
  "conv-3": [
    {
      id: "m301",
      conversationId: "conv-3",
      sender: "customer",
      content: "Do you support custom Shopify Plus checkout extensions in your Instagram DM flow?",
      confidenceScore: 62,
      decisionRoute: "escalated_pending",
      createdAt: "2026-07-20T15:02:00Z",
    },
  ],
};

export const initialLearningQueue: LearningItem[] = [
  {
    id: "lq-1",
    question: "Do you support custom Shopify Plus checkout extensions in your Instagram DM flow?",
    customerUsername: "marcus_retail",
    conversationId: "conv-3",
    aiSuggestion: "Zawr supports standard URL links for checkout. For direct in-DM Shopify Plus native extensions, custom webhook bridges can be configured during onboarding.",
    status: "pending",
    category: "services",
    createdAt: "2026-07-20T15:02:00Z",
  },
  {
    id: "lq-2",
    question: "What is your latency SLA for enterprise accounts handling over 500k monthly messages?",
    customerUsername: "tech_founder_sam",
    conversationId: "conv-4",
    aiSuggestion: "Enterprise accounts receive dedicated sub-second latency SLA (<500ms) backed by custom Groq or Ollama dedicated instances.",
    status: "pending",
    category: "support",
    createdAt: "2026-07-20T13:45:00Z",
  },
];

export const initialLogs: AiLog[] = [
  {
    id: "log-1",
    conversationId: "conv-1",
    customerUsername: "alex_growth",
    prompt: "Customer asked for agency multi-account pricing tier.",
    knowledgeUsed: ["Pricing Tiers & Inclusions"],
    confidenceScore: 98,
    provider: "gemini",
    model: "gemini-1.5-flash",
    tokensTotal: 142,
    latencyMs: 840,
    decisionRoute: "auto_reply",
    ownerApproved: true,
    replyText: "Hello Alex! Thanks for reaching out to Zawr. For multi-account agencies...",
    timestamp: "2026-07-20T14:16:00Z",
  },
  {
    id: "log-2",
    conversationId: "conv-3",
    customerUsername: "marcus_retail",
    prompt: "Customer asked about Shopify Plus checkout extensions in IG DM.",
    knowledgeUsed: [],
    confidenceScore: 62,
    provider: "gemini",
    model: "gemini-1.5-flash",
    tokensTotal: 88,
    latencyMs: 620,
    decisionRoute: "escalated_pending",
    ownerApproved: false,
    replyText: "[Escalated to Owner Learning Queue]",
    timestamp: "2026-07-20T15:02:00Z",
  },
];

export const initialDiagnostics: SystemDiagnostics = {
  instagramConnected: true,
  databaseHealthy: true,
  aiProviderConnected: true,
  webhookActive: true,
  deploymentHealthy: true,
  storageHealthy: true,
  knowledgeIndexedCount: 42,
  notificationsWorking: true,
  missingKeys: [],
};
